!googlify command
Minehut/MinehutBOT pull request #146
Opened 2021-10-13 22:57 UTC by LouisLit

Addition of `!googlify`, allowing users to turn cmd args into a google search link for encouraging others to use an amazing platform called Google.

Initial issue about the command: https://github.com/Minehut/Meta/issues/822

2021-10-13 23:29 UTC, Sniped requested changes
Overall, I think that the addition of this command is unneeded. This will also just introduce spam into the Discord, as this closed meta issue states: https://github.com/Minehut/Meta/issues/306. Additionally, this closed PR proposes this exact command: https://github.com/Minehut/MinehutBOT/pull/66.

2021-10-13 23:29 UTC, Sniped commented on src/command/info/googlify.ts
> +        super('google', {
Space indents are inconsistent with the code base, use tab indents.

2021-10-13 23:29 UTC, Sniped commented on src/command/info/googlify.ts
> +        msg.channel.send({ content: `https://google.com/search?q=${encodeURI(search.replace(/ /gi, '+'))}` });
I believe that this could be prettified a bit using Prettier. Prettier is supported on various code editors and IDEs, the list is [here](https://prettier.io/docs/en/editors.html).

2021-10-13 23:29 UTC, Sniped commented on src/command/info/googlify.ts
> +                ussage: '<query>',
Typo here on `usage`

2021-10-13 23:29 UTC, Sniped commented on src/command/info/googlify.ts
> +                    id: 'search',
`query` sounds like a better id value for this

2021-10-15 15:23 UTC, jellz requested changes
This kind of command belongs in the Utility category & folder. The Info category is for looking up information directly through the bot (i.e. commands like !server, !addon & !networkstats).

Maybe add a few more examples? Also, I think an alias like "search" would be nice.

I would also suggest editing the command description to be something like "Provides Google search link for query" or something along those lines - IMO the current one could use some polish, but that's ultimately up to you.

I agree with Facto about this command not really being a necessary addition.

2021-12-15 23:02 UTC, BennyDoesStuff commented
Closing PR until suggested changes are implemented.

2021-12-15 23:02 UTC, closed without merging