Activity Command
Minehut/MinehutBOT pull request #153
Opened 2022-01-05 08:04 UTC by Prorickey

I added the activity command so that users can create activities without needing better discord or anything weird. Discord's new activities are not fully on all servers yet but can be accessed with discord bots. I also had to add a new intent to get this to work.

2022-01-05 10:19 UTC, jellz requested changes
- What is the reason for changing the TypeScript config file?
- Why is the map of activity names -> snowflakes a Discord.js Collection, rather than a plain Map or Object? Also, this doesn't need to be created every time the command is executed
- I would suggest the logic for sending the request to the Discord API be done in a separate function
- The indentation is off, you should probably run Prettier on the file (with the repo config)

2022-01-05 17:43 UTC, Sniped requested changes
I believe that the mappings for the activity names and activity snowflakes can be placed into another file, probably `constants.ts`. You can use this to create a list of possible activity names instead of hard coding them into the start prompt as you did in line 23. I also believe that you can declare a custom arg type and do your validation there (verifying that the activity exists, etc). 

All in all, is such a command really necessary for the bot? I see why the need for the command could be necessary now, as not everyone has the ability to start activities on the vanilla Discord client. Though, what use would this command be when everyone can access activities on the Discord client, which might not be that long of a wait?

2022-01-05 17:43 UTC, Sniped commented on src/command/info/activity.ts
> +					id: 'activityname',
This naming is inconsistent with the codebase, use camel case for the variable name.

`activityname` would therefore become `activityName`

2022-01-05 17:43 UTC, Sniped commented on src/command/info/activity.ts
> +		applications.set("youtube", "880218394199220334");
The use of quotes for string literal declarations is inconsistent with the codebase. As jellz said, however, running Prettier with the configuration would fix this inconsistency.

2022-01-05 17:43 UTC, Sniped commented on src/command/info/activity.ts
> +        await msg.channel.send(`Enjoy the games! https://discord.gg/${inviteData.code} (Click the link, not the embed)`);
There should be an emoji indicating that the command was successfully executed, such as the success emoji.

2022-01-05 17:43 UTC, Sniped commented on src/command/info/activity.ts
> +			await msg.channel.send(`${msg.author}, there was an unknown error while generating the link, please try again.`);
Rather than pinging the message author, you should just use the `EMOJI_CROSS` env value as you did previously in this command.

2022-01-05 17:43 UTC, Sniped commented on src/command/info/activity.ts
> +		if(inviteData.code == null) {
You don't need to check if `inviteData.code` is equal to `null`, you can just use `!inviteData.code` as it means the same thing.

2022-01-27 16:11 UTC, BennyDoesStuff commented
Closing PR, please address the requested changes provided.

2022-01-27 16:11 UTC, closed without merging