Channel Cooldown Command
Minehut/MinehutBOT pull request #68
Opened 2020-10-26 02:29 UTC by Sniped

Adds a command to set the cooldown for a channel so moderators can set cooldowns in a channel without needing to ask a senior moderator to do so.

2020-11-18 23:59 UTC, theminecoder requested changes
@Sniped Instead of having to specify the channel can we just force it to use the current typed in?

2020-11-19 00:02 UTC, Sniped commented
> @Sniped Instead of having to specify the channel can we just force it to use the current typed in?

Do you mean making the channel argument optional or just completely removing the argument all together?

2020-11-19 00:04 UTC, theminecoder commented
There really shouldnt need to be a time where you need to specify a channel you can’t directly type in, so I think just remove it.

> On 19 Nov 2020, at 11:02 am, Facto <notifications@github.com> wrote:
> 
> 
> @Sniped <https://github.com/Sniped> Instead of having to specify the channel can we just force it to use the current typed in?
> 
> Do you mean making the channel argument optional or just completely removing the argument all together?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/Minehut/MinehutBOT/pull/68#issuecomment-730033893>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAKU5EDTSF2Y7SMBW7CEBIDSQROC5ANCNFSM4S6Y7HSA>.
>

2020-11-19 00:57 UTC, theminecoder approved these changes

2020-11-19 00:57 UTC, merged

2020-11-23 01:49 UTC, jellz commented
Huge missed opportunity to complete [this issue](https://github.com/Minehut/Meta/issues/381) in this

2020-11-24 00:44 UTC, Sniped commented
> Huge missed opportunity to complete [this issue](https://github.com/Minehut/Meta/issues/381) in this

I was going to do so but didn't get the chance before it was merged, will likely add custom cooldowns to this command and link the PR to that issue (maybe a flag in the cooldown command?).