Add tag categorization
Minehut/MinehutBOT pull request #89
Opened 2021-01-09 16:59 UTC by honkling

Adds:
- **!tag setsection <tag name> <section>**
- **!tag set <section> <tag name> <tag content>**
- **!tags** shows tags in categories. Tags without categories will appear in the category **Uncategorized**

2021-01-09 18:21 UTC, jellz commented
Could you propose some categories for the existing tags? I noticed Informative in one command example but all tags are informative lol

2021-01-09 19:09 UTC, honkling commented
> Could you propose some categories for the existing tags? I noticed Informative in one command example but all tags are informative lol

I purely just put "informative" as an example word, there aren't any hard coded categories. Anyways, there could be ones like `panel`, `permissions`, `world`, `discord`, etc.

2021-01-11 02:35 UTC, draem requested changes

2021-01-11 02:35 UTC, draem commented on src/command/tag/info.ts
> +				tag.aliases.map((a: any) => `\`${a}\``).join(', '),
don't use any please
~draem

2021-01-11 02:35 UTC, draem commented on src/command/tag/list.ts
> +		const fields: any = {};
don't use any please

2021-01-11 02:35 UTC, draem commented on src/command/tag/list.ts
> +				field.map((t: any) => `\`${t.name}\``).join(', '),
don't use any please

2021-01-11 03:23 UTC, theminecoder commented
Please merge master into this and update the commands to handle the updated roles

2021-01-11 04:13 UTC, honkling commented
That should be everything. If I've missed something, please comment :)

2021-01-11 07:55 UTC, theminecoder approved these changes
Looks good. Just giving sr mods/managers some heads up before this is merged so tags can immediately be put in the right sections.

2021-01-13 02:53 UTC, merged